# Two Dimensional Array

## Create Two Dimensional Array

- Row 1 - 11, 15, 10, 6
- Row 2 - 10, 14, 11, 5
- Row 3 - 12, 17, 22, 8
- Row 4 - 15, 18, 14, 9

In [1]:
import numpy as np

In [2]:
two_dimensional_array = np.array([
    [11, 15, 10, 6],
    [10, 14, 11, 5],
    [12, 17, 22, 8],
    [15, 18, 14, 9],
])
print(two_dimensional_array)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 22  8]
 [15 18 14  9]]


## Insertion - Two Dimensional Array

In [4]:
new_two_dimensional_array = np.insert(
    two_dimensional_array, 1, [[1, 2, 3, 4]], axis=0
)
print(new_two_dimensional_array)

[[11 15 10  6]
 [ 1  2  3  4]
 [10 14 11  5]
 [12 17 22  8]
 [15 18 14  9]]


In [5]:
new_two_dimensional_array = np.append(
    two_dimensional_array, [[1, 2, 3, 4]], axis=0)
print(new_two_dimensional_array)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 22  8]
 [15 18 14  9]
 [ 1  2  3  4]]


## Accessing an Element of Two Dimensional Array

In [7]:
def accessElement(array, row_index, col_index):
    if row_index >= len(array) or col_index >= len(array[0]):
        print('Incorrect index')
    else:
        print(array[row_index][col_index])


accessElement(two_dimensional_array, 3, 2)


14


## Traversal - Two Dimensional Array

In [8]:
def traverseElement(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])


traverseElement(two_dimensional_array)


11
15
10
6
10
14
11
5
12
17
22
8
15
18
14
9


## Searching for an Element in Two Dimensional Array

In [9]:
def searchElement(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'The value is located at index {} {}'.format(i, j)

    return 'The element is not found'


print(searchElement(two_dimensional_array, 22))


The value is located at index 2 2


## Deletion - Two Dimensional Array

In [10]:
new_two_dimensional_array = np.delete(two_dimensional_array, 1, axis=0)
print(new_two_dimensional_array)


[[11 15 10  6]
 [12 17 22  8]
 [15 18 14  9]]


| Operation                          | Time Complexity | Space Complexity |
|------------------------------------|-----------------|------------------|
| Creating an empty array            | O(1)            | O(1)             |
| Creating an array with elements    | O(mn)           | O(mn)            |
| Inserting a column/row in an array | O(mn)           | O(mn)            |
| Traversing a given array           | O(mn)           | O(1)             |
| Accessing a given cell             | O(1)            | O(1)             |
| Searching a given value            | O(mn)           | O(1)             |
| Deleting a column/row              | O(mn)           | O(mn)            |